title = "if err != nil"
baseURL = 'https://if-not-nil.github.io'
languageCode = 'en-us'
enableRobotsTXT = "true"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
# "relatedtext" is the text that appears above the tag list at the bottom of pages.
    relatedtext = "related"
    favicon = "/favicon.gif"
	default_image = "/static/cat.png"
#list items
    datesinlist = true
    authorsinlist = true

#footer items
    nextprev = true
    taglist = true
    showrss = true

[privacy]
[privacy.youTube]
disable = false
privacyEnhanced = true

[mediaTypes."image/webp"]
suffixes = ["webp"]

[outputFormats]
[outputFormats.webp]
mediaType = "image/webp"
relURL = true
